### ISSUE TITLE
你好，之前阅读了您的Linux与Windows 10用grub引导教程，自己折腾时出了问题，请指教

### ISSUE THREAD

**Issue by leozxzx** [WincerChan/MyBlog#34]
Tivsae你好，之前阅读了您的Linux与Windows 10用grub引导教程，在卸载manjaro，新装deepin时遇到了问题

我的机器宏碁，有两块盘，采用UEFI+GPT模式安装。
固态上有win10，原本有个100mb大小的efi区。原先manjaro安装时把引导也放在了这里。

DEEPIN给了机械硬盘，安装时分了一个300mb的efi。

今天进了WINDOWS捣鼓了一阵以后发现无法再进入grub，于是用easyefi和BOOTICE进行调整（bios里的Boot调整顺序只有windows boot manager以及几块盘符，没有Linux或者deepin，无法通过调整顺序强制先启动DEEPIN）
发现无论怎样用软件调整boot顺序，只要回到windows，启动顺序又会回到windows boot manager第一位的状态。

当时安装Manjaro时把他的引导也放在win所在的固态的efi里，按教程，在windows下进入了管理员命令行（win+x，再按a，标题是"管理员:power shell"），输入了命令：
bcdedit /set '{bootmgr}' path \EFI\Manjaro\grubx64.efi

结果导致现在在uefi启动序列里有两个windows boot manager，
其中一个是指向\EFI\Manjaro\grubx64.efi
另一个是指向\EFI\Microsoft\Boot\bootmgfw.efi

第一个无论是easyefi还是BOOTICE删除后再次进入windows都会再次出现并且位于序列第一位。
请问该用什么命令取消“bcdedit /set '{bootmgr}' path \EFI\Manjaro\grubx64.efi”的效果？

PS：我删除manjaro时直接格掉了系统所在盘符，在固态的efi盘符下删除了manjaro文件夹，清空了boot文件夹。

**Comment by WincerChan** [comment]
试试 bcdedit /set '{bootmgr}' path \EFI\Microsoft\Boot\bootmgfw.efi，把 efi 的顺序重新设置为 Windows。另外可以查阅一下 bcdedit 的用法，应该是可以直接删除掉一个启动项的

**Comment by leozxzx** [comment]
感谢，问题解决，输入指令后重启出现了deepin的grub界面，回win10后用BOOTICE查看发现原本指向\EFI\Manjaro\grubx64.efi的windows boot manager已经消失。

**Comment by WincerChan** [comment]
OK，解决了就好。
